export const FETCH_CLOTHES_START = 'FETCH_CLOTHES_START';
export const FETCH_CLOTHES_SUCCESS = 'FETCH_CLOTHES_SUCCESS';
export const FETCH_CLOTHES_FAIL = 'FETCH_CLOTHES_FAIL';
export const SET_CLOTHES = 'SET_CLOTHES';

export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILS = 'FETCH_ARTICLE_FAILS';
export const SET_ARTICLE = 'SET_ARTICLE';
export const FILTER_RESULTS = 'FILTER_RESULTS';

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const WELCOME_USER = 'WELCOME_USER';
export const LOG_IN = 'LOG_IN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const FAVORITE_CLOTHES = 'FAVORITE_CLOTHES';
export const GET_FAVORITE_CLOTHES = 'GET_FAVORITE_CLOTHES';

export const GET_BASKET_ARTICLE = 'GET_BASKET_ARTICLE';
export const SET_BASKET_ARTICLE = 'SET_BASKET_ARTICLE';
export const FAIL_BASKET_ARTICLE = 'FAIL_BASKET_ARTICLE';
export const GET_BASKET_FAILS = 'GET_BASKET_FAILS';